version: "3.9"
services:
  api-template:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=api
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=api
    volumes:
      - ./data:/var/lib/mysql